// {
//     "name": "Pedigree 100g",
//     "photo": "https://images-na.ssl-images-amazon.com/images/I/812PqI0PadL._AC_UL604_SR604,400_.jpg",
//     "Note": "",
//     "Quantity": 54,
//     "Animal": "food"
// },
export const InventoryData = [

        {
            "Medical Conditions": "Asia",
            "Breed": "Manufacturing",
            "Notes": "Resellers",
            "Units": 3,
            "Name": "Columbia Solar",
            "Animal": "Cabras",
            "Amount": 4670.0,
            "Food Quantity": "0.3314285714285714285714285714",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1476
        },
        {
            "Medical Conditions": "Australia",
            "Breed": "Telecom",
            "Notes": "Consultants",
            "Units": 2,
            "Name": "Supply Warehous",
            "Animal": "Caballos",
            "Amount": 4440.0,
            "Food Quantity": "0.224",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1477
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Telecom",
            "Notes": "Direct",
            "Units": 4,
            "Name": "Energy Systems",
            "Animal": "Pavos",
            "Amount": 8280.0,
            "Food Quantity": "0.32",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1478
        },
        {
            "Medical Conditions": "Europe",
            "Breed": "Telecom",
            "Notes": "Retail",
            "Units": 1,
            "Name": "Supply Warehous",
            "Animal": "Vacas",
            "Amount": 1590.0,
            "Food Quantity": "0.205",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1479
        },
        {
            "Medical Conditions": "Asia",
            "Breed": "Insurance",
            "Notes": "Resellers",
            "Units": 2,
            "Name": "Columbia Solar",
            "Animal": "Caballos",
            "Amount": 4390.0,
            "Food Quantity": "0.244",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1480
        },
        {
            "Medical Conditions": "South America",
            "Breed": "Telecom",
            "Notes": "Direct",
            "Units": 2,
            "Name": "Get Solar Inc",
            "Animal": "Vacas",
            "Amount": 3720.0,
            "Food Quantity": "0.14",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1481
        },
        {
            "Medical Conditions": "Asia",
            "Breed": "Health",
            "Notes": "Direct",
            "Units": 3,
            "Name": "Health Plus Inc",
            "Animal": "Cabras",
            "Amount": 4810.0,
            "Food Quantity": "0.2514285714285714285714285714",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1482
        },
        {
            "Medical Conditions": "Europe",
            "Breed": "Insurance",
            "Notes": "Resellers",
            "Units": 3,
            "Name": "Gemini Stores",
            "Animal": "Pavos",
            "Amount": 6470.0,
            "Food Quantity": "0.1244444444444444444444444444",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1483
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Health",
            "Notes": "VARs",
            "Units": 4,
            "Name": "Market Eco",
            "Animal": "Cabras",
            "Amount": 6580.0,
            "Food Quantity": "0.24",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1484
        },
        {
            "Medical Conditions": "Australia",
            "Breed": "Telecom",
            "Notes": "Resellers",
            "Units": 4,
            "Name": "Get Solar Inc",
            "Animal": "Vacas",
            "Amount": 7670.0,
            "Food Quantity": "0.165",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1485
        },
        {
            "Medical Conditions": "South America",
            "Breed": "Insurance",
            "Notes": "Resellers",
            "Units": 2,
            "Name": "Discovery Systems",
            "Animal": "Caballos",
            "Amount": 4690.0,
            "Food Quantity": "0.124",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1486
        },
        {
            "Medical Conditions": "Europe",
            "Breed": "Manufacturing",
            "Notes": "Direct",
            "Units": 1,
            "Name": "Johnson & Assoc",
            "Animal": "Caballos",
            "Amount": 1930.0,
            "Food Quantity": "0.228",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1487
        },
        {
            "Medical Conditions": "Australia",
            "Breed": "Health",
            "Notes": "Consultants",
            "Units": 4,
            "Name": "Apollo Inc",
            "Animal": "Caballos",
            "Amount": 9400.0,
            "Food Quantity": "0.24",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1488
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Health",
            "Notes": "Direct",
            "Units": 4,
            "Name": "Get Solar Inc",
            "Animal": "Cabras",
            "Amount": 6450.0,
            "Food Quantity": "0.3142857142857142857142857143",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1489
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Banking",
            "Notes": "Consultants",
            "Units": 2,
            "Name": "Columbia Solar",
            "Animal": "Pavos",
            "Amount": 3910.0,
            "Food Quantity": "0.2622222222222222222222222222",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1490
        },
        {
            "Medical Conditions": "Asia",
            "Breed": "Banking",
            "Notes": "Consultants",
            "Units": 3,
            "Name": "Beacon Systems",
            "Animal": "Caballos",
            "Amount": 6890.0,
            "Food Quantity": "0.244",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1491
        },
        {
            "Medical Conditions": "Australia",
            "Breed": "Banking",
            "Notes": "Resellers",
            "Units": 3,
            "Name": "Beacon Systems",
            "Animal": "Pavos",
            "Amount": 6350.0,
            "Food Quantity": "0.1777777777777777777777777778",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1492
        },
        {
            "Medical Conditions": "South America",
            "Breed": "Health",
            "Notes": "VARs",
            "Units": 1,
            "Name": "Market Eco",
            "Animal": "Pavos",
            "Amount": 1950.0,
            "Food Quantity": "0.1333333333333333333333333333",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1493
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Insurance",
            "Notes": "Resellers",
            "Units": 3,
            "Name": "Apollo Inc",
            "Animal": "Vacas",
            "Amount": 5640.0,
            "Food Quantity": "0.18",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1494
        },
        {
            "Medical Conditions": "Asia",
            "Breed": "Insurance",
            "Notes": "Consultants",
            "Units": 1,
            "Name": "Green Energy Inc",
            "Animal": "Caballos",
            "Amount": 1920.0,
            "Food Quantity": "0.232",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1495
        },
        {
            "Medical Conditions": "Europe",
            "Breed": "Health",
            "Notes": "VARs",
            "Units": 1,
            "Name": "Health Plus Inc",
            "Animal": "Caballos",
            "Amount": 1930.0,
            "Food Quantity": "0.228",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1496
        },
        {
            "Medical Conditions": "Europe",
            "Breed": "Banking",
            "Notes": "Consultants",
            "Units": 1,
            "Name": "Beacon Systems",
            "Animal": "Pavos",
            "Amount": 1750.0,
            "Food Quantity": "0.2222222222222222222222222222",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1497
        },
        {
            "Medical Conditions": "Europe",
            "Breed": "Telecom",
            "Notes": "Resellers",
            "Units": 1,
            "Name": "Arthur & Sons",
            "Animal": "Pavos",
            "Amount": 1820.0,
            "Food Quantity": "0.1911111111111111111111111111",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1498
        },
        {
            "Medical Conditions": "Australia",
            "Breed": "Health",
            "Notes": "Consultants",
            "Units": 2,
            "Name": "Market Eco",
            "Animal": "Caballos",
            "Amount": 4800.0,
            "Food Quantity": "0.08",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1499
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Insurance",
            "Notes": "Retail",
            "Units": 2,
            "Name": "System Integrators",
            "Animal": "Pavos",
            "Amount": 3940.0,
            "Food Quantity": "0.2488888888888888888888888889",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1500
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Telecom",
            "Notes": "VARs",
            "Units": 4,
            "Name": "Beacon Systems",
            "Animal": "Caballos",
            "Amount": 9530.0,
            "Food Quantity": "0.188",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1501
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Health",
            "Notes": "VARs",
            "Units": 4,
            "Name": "Health Plus Inc",
            "Animal": "Vacas",
            "Amount": 7720.0,
            "Food Quantity": "0.14",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1502
        },
        {
            "Medical Conditions": "Europe",
            "Breed": "Insurance",
            "Notes": "Direct",
            "Units": 1,
            "Name": "Get Solar Inc",
            "Animal": "Vacas",
            "Amount": 1290.0,
            "Food Quantity": "0.355",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1503
        },
        {
            "Medical Conditions": "South America",
            "Breed": "Health",
            "Notes": "Direct",
            "Units": 3,
            "Name": "Apollo Inc",
            "Animal": "Gallinas",
            "Amount": 4270.0,
            "Food Quantity": "0.1533333333333333333333333333",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1504
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Insurance",
            "Notes": "Resellers",
            "Units": 1,
            "Name": "System Integrators",
            "Animal": "Caballos",
            "Amount": 1770.0,
            "Food Quantity": "0.292",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1505
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Health",
            "Notes": "VARs",
            "Units": 1,
            "Name": "System Integrators",
            "Animal": "Caballos",
            "Amount": 2320.0,
            "Food Quantity": "0.072",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1506
        },
        {
            "Medical Conditions": "Europe",
            "Breed": "Banking",
            "Notes": "Resellers",
            "Units": 3,
            "Name": "Green Energy Inc",
            "Animal": "Vacas",
            "Amount": 5310.0,
            "Food Quantity": "0.345",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1507
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Health",
            "Notes": "VARs",
            "Units": 2,
            "Name": "Mercury Solar",
            "Animal": "Pavos",
            "Amount": 4140.0,
            "Food Quantity": "0.16",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1508
        },
        {
            "Medical Conditions": "Asia",
            "Breed": "Telecom",
            "Notes": "Direct",
            "Units": 3,
            "Name": "Energy Systems",
            "Animal": "Caballos",
            "Amount": 7190.0,
            "Food Quantity": "0.124",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1509
        },
        {
            "Medical Conditions": "Europe",
            "Breed": "Health",
            "Notes": "Consultants",
            "Units": 3,
            "Name": "Health Plus Inc",
            "Animal": "Vacas",
            "Amount": 5360.0,
            "Food Quantity": "0.32",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1510
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Banking",
            "Notes": "Resellers",
            "Units": 3,
            "Name": "Supply Warehous",
            "Animal": "Caballos",
            "Amount": 7070.0,
            "Food Quantity": "0.172",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1511
        },
        {
            "Medical Conditions": "North America",
            "Breed": "Banking",
            "Notes": "VARs",
            "Units": 1,
            "Name": "Mercury Solar",
            "Animal": "Pavos",
            "Amount": 1590.0,
            "Food Quantity": "0.2933333333333333333333333333",
            "BirthDate": "2020-05-15T00:00:00",
            "Gender": [],
            "Id": 1512
        }]
