// {
//     "name": "Pedigree 100g",
//     "photo": "https://images-na.ssl-images-amazon.com/images/I/812PqI0PadL._AC_UL604_SR604,400_.jpg",
//     "Note": "",
//     "Quantity": 54,
//     "Animal": "food"
// },
export const InventoryData =
    [
      {
        "Medical Conditions": "Obesity",
        "Breed": "Manufacturing",
        "Notes": "Resellers",
        "Units": 3,
        "Name": "Columbia Solar",
        "Animal": "Gallinas",
        "Amount": 4670,
        "Food Quantity": "0.3314285714285714285714285714",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1476,
        "age": 11,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Arthritis",
        "Breed": "Telecom",
        "Notes": "Consultants",
        "Units": 2,
        "Name": "Supply Warehous",
        "Animal": "Gallinas",
        "Amount": 4440,
        "Food Quantity": "0.224",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1477,
        "age": 16,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Telecom",
        "Notes": "Direct",
        "Units": 4,
        "Name": "Energy Systems",
        "Animal": "Gallinas",
        "Amount": 8280,
        "Food Quantity": "0.32",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1478,
        "age": 0,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Telecom",
        "Notes": "Retail",
        "Units": 1,
        "Name": "Supply Warehous",
        "Animal": "Gallinas",
        "Amount": 1590,
        "Food Quantity": "0.205",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1479,
        "age": 9,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 2,
        "Name": "Columbia Solar",
        "Animal": "Gallinas",
        "Amount": 4390,
        "Food Quantity": "0.244",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1480,
        "age": 9,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Urinary Problems",
        "Breed": "Telecom",
        "Notes": "Direct",
        "Units": 2,
        "Name": "Get Solar Inc",
        "Animal": "Gallinas",
        "Amount": 3720,
        "Food Quantity": "0.14",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1481,
        "age": 6,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Health",
        "Notes": "Direct",
        "Units": 3,
        "Name": "Health Plus Inc",
        "Animal": "Gallinas",
        "Amount": 4810,
        "Food Quantity": "0.2514285714285714285714285714",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1482,
        "age": 1,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 3,
        "Name": "Gemini Stores",
        "Animal": "Gallinas",
        "Amount": 6470,
        "Food Quantity": "0.1244444444444444444444444444",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1483,
        "age": 4,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Health",
        "Notes": "VARs",
        "Units": 4,
        "Name": "Market Eco",
        "Animal": "Gallinas",
        "Amount": 6580,
        "Food Quantity": "0.24",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1484,
        "age": 20,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Arthritis",
        "Breed": "Telecom",
        "Notes": "Resellers",
        "Units": 4,
        "Name": "Get Solar Inc",
        "Animal": "Gallinas",
        "Amount": 7670,
        "Food Quantity": "0.165",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1485,
        "age": 16,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Urinary Problems",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 2,
        "Name": "Discovery Systems",
        "Animal": "Gallinas",
        "Amount": 4690,
        "Food Quantity": "0.124",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1486,
        "age": 16,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Manufacturing",
        "Notes": "Direct",
        "Units": 1,
        "Name": "Johnson & Assoc",
        "Animal": "Gallinas",
        "Amount": 1930,
        "Food Quantity": "0.228",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1487,
        "age": 5,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Arthritis",
        "Breed": "Health",
        "Notes": "Consultants",
        "Units": 4,
        "Name": "Apollo Inc",
        "Animal": "Gallinas",
        "Amount": 9400,
        "Food Quantity": "0.24",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1488,
        "age": 0,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Health",
        "Notes": "Direct",
        "Units": 4,
        "Name": "Get Solar Inc",
        "Animal": "Gallinas",
        "Amount": 6450,
        "Food Quantity": "0.3142857142857142857142857143",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1489,
        "age": 10,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Banking",
        "Notes": "Consultants",
        "Units": 2,
        "Name": "Columbia Solar",
        "Animal": "Gallinas",
        "Amount": 3910,
        "Food Quantity": "0.2622222222222222222222222222",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1490,
        "age": 7,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Banking",
        "Notes": "Consultants",
        "Units": 3,
        "Name": "Beacon Systems",
        "Animal": "Gallinas",
        "Amount": 6890,
        "Food Quantity": "0.244",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1491,
        "age": 2,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Manufacturing",
        "Notes": "Resellers",
        "Units": 3,
        "Name": "Columbia Solar",
        "Animal": "Obejas",
        "Amount": 4670,
        "Food Quantity": "0.3314285714285714285714285714",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1476,
        "age": 8,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Arthritis",
        "Breed": "Telecom",
        "Notes": "Consultants",
        "Units": 2,
        "Name": "Supply Warehous",
        "Animal": "Obejas",
        "Amount": 4440,
        "Food Quantity": "0.224",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1477,
        "age": 0,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Telecom",
        "Notes": "Direct",
        "Units": 4,
        "Name": "Energy Systems",
        "Animal": "Obejas",
        "Amount": 8280,
        "Food Quantity": "0.32",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1478,
        "age": 20,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Telecom",
        "Notes": "Retail",
        "Units": 1,
        "Name": "Supply Warehous",
        "Animal": "Obejas",
        "Amount": 1590,
        "Food Quantity": "0.205",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1479,
        "age": 7,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 2,
        "Name": "Columbia Solar",
        "Animal": "Obejas",
        "Amount": 4390,
        "Food Quantity": "0.244",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1480,
        "age": 20,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Urinary Problems",
        "Breed": "Telecom",
        "Notes": "Direct",
        "Units": 2,
        "Name": "Get Solar Inc",
        "Animal": "Obejas",
        "Amount": 3720,
        "Food Quantity": "0.14",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1481,
        "age": 19,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Health",
        "Notes": "Direct",
        "Units": 3,
        "Name": "Health Plus Inc",
        "Animal": "Obejas",
        "Amount": 4810,
        "Food Quantity": "0.2514285714285714285714285714",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1482,
        "age": 11,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 3,
        "Name": "Gemini Stores",
        "Animal": "Obejas",
        "Amount": 6470,
        "Food Quantity": "0.1244444444444444444444444444",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1483,
        "age": 5,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Health",
        "Notes": "VARs",
        "Units": 4,
        "Name": "Market Eco",
        "Animal": "Obejas",
        "Amount": 6580,
        "Food Quantity": "0.24",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1484,
        "age": 20,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Manufacturing",
        "Notes": "Resellers",
        "Units": 3,
        "Name": "Columbia Solar",
        "Animal": "Gansos",
        "Amount": 4670,
        "Food Quantity": "0.3314285714285714285714285714",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1476,
        "age": 15,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Arthritis",
        "Breed": "Telecom",
        "Notes": "Consultants",
        "Units": 2,
        "Name": "Supply Warehous",
        "Animal": "Gansos",
        "Amount": 4440,
        "Food Quantity": "0.224",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1477,
        "age": 7,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Telecom",
        "Notes": "Direct",
        "Units": 4,
        "Name": "Energy Systems",
        "Animal": "Gansos",
        "Amount": 8280,
        "Food Quantity": "0.32",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1478,
        "age": 0,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Telecom",
        "Notes": "Retail",
        "Units": 1,
        "Name": "Supply Warehous",
        "Animal": "Gansos",
        "Amount": 1590,
        "Food Quantity": "0.205",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1479,
        "age": 9,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 2,
        "Name": "Columbia Solar",
        "Animal": "Gansos",
        "Amount": 4390,
        "Food Quantity": "0.244",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1480,
        "age": 2,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Urinary Problems",
        "Breed": "Telecom",
        "Notes": "Direct",
        "Units": 2,
        "Name": "Get Solar Inc",
        "Animal": "Gansos",
        "Amount": 3720,
        "Food Quantity": "0.14",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1481,
        "age": 2,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Health",
        "Notes": "Direct",
        "Units": 3,
        "Name": "Health Plus Inc",
        "Animal": "Gansos",
        "Amount": 4810,
        "Food Quantity": "0.2514285714285714285714285714",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1482,
        "age": 15,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 3,
        "Name": "Gemini Stores",
        "Animal": "Gansos",
        "Amount": 6470,
        "Food Quantity": "0.1244444444444444444444444444",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1483,
        "age": 16,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Health",
        "Notes": "VARs",
        "Units": 4,
        "Name": "Market Eco",
        "Animal": "Gansos",
        "Amount": 6580,
        "Food Quantity": "0.24",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1484,
        "age": 10,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Arthritis",
        "Breed": "Telecom",
        "Notes": "Resellers",
        "Units": 4,
        "Name": "Get Solar Inc",
        "Animal": "Gansos",
        "Amount": 7670,
        "Food Quantity": "0.165",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1485,
        "age": 8,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Urinary Problems",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 2,
        "Name": "Discovery Systems",
        "Animal": "Gansos",
        "Amount": 4690,
        "Food Quantity": "0.124",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1486,
        "age": 17,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Manufacturing",
        "Notes": "Direct",
        "Units": 1,
        "Name": "Johnson & Assoc",
        "Animal": "Gansos",
        "Amount": 1930,
        "Food Quantity": "0.228",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1487,
        "age": 0,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Arthritis",
        "Breed": "Health",
        "Notes": "Consultants",
        "Units": 4,
        "Name": "Apollo Inc",
        "Animal": "Gansos",
        "Amount": 9400,
        "Food Quantity": "0.24",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1488,
        "age": 13,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Health",
        "Notes": "Direct",
        "Units": 4,
        "Name": "Get Solar Inc",
        "Animal": "Gansos",
        "Amount": 6450,
        "Food Quantity": "0.3142857142857142857142857143",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1489,
        "age": 4,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Banking",
        "Notes": "Consultants",
        "Units": 2,
        "Name": "Columbia Solar",
        "Animal": "Gansos",
        "Amount": 3910,
        "Food Quantity": "0.2622222222222222222222222222",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1490,
        "age": 18,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Banking",
        "Notes": "Consultants",
        "Units": 3,
        "Name": "Beacon Systems",
        "Animal": "Gansos",
        "Amount": 6890,
        "Food Quantity": "0.244",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1491,
        "age": 3,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Manufacturing",
        "Notes": "Resellers",
        "Units": 3,
        "Name": "Columbia Solar",
        "Animal": "Cabras",
        "Amount": 4670,
        "Food Quantity": "0.3314285714285714285714285714",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1476,
        "age": 2,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Arthritis",
        "Breed": "Telecom",
        "Notes": "Consultants",
        "Units": 2,
        "Name": "Supply Warehous",
        "Animal": "Caballos",
        "Amount": 4440,
        "Food Quantity": "0.224",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1477,
        "age": 4,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Telecom",
        "Notes": "Direct",
        "Units": 4,
        "Name": "Energy Systems",
        "Animal": "Pavos",
        "Amount": 8280,
        "Food Quantity": "0.32",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1478,
        "age": 6,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Telecom",
        "Notes": "Retail",
        "Units": 1,
        "Name": "Supply Warehous",
        "Animal": "Vacas",
        "Amount": 1590,
        "Food Quantity": "0.205",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1479,
        "age": 20,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 2,
        "Name": "Columbia Solar",
        "Animal": "Caballos",
        "Amount": 4390,
        "Food Quantity": "0.244",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1480,
        "age": 11,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Urinary Problems",
        "Breed": "Telecom",
        "Notes": "Direct",
        "Units": 2,
        "Name": "Get Solar Inc",
        "Animal": "Vacas",
        "Amount": 3720,
        "Food Quantity": "0.14",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1481,
        "age": 3,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Health",
        "Notes": "Direct",
        "Units": 3,
        "Name": "Health Plus Inc",
        "Animal": "Cabras",
        "Amount": 4810,
        "Food Quantity": "0.2514285714285714285714285714",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1482,
        "age": 17,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 3,
        "Name": "Gemini Stores",
        "Animal": "Pavos",
        "Amount": 6470,
        "Food Quantity": "0.1244444444444444444444444444",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1483,
        "age": 13,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Health",
        "Notes": "VARs",
        "Units": 4,
        "Name": "Market Eco",
        "Animal": "Cabras",
        "Amount": 6580,
        "Food Quantity": "0.24",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1484,
        "age": 14,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Arthritis",
        "Breed": "Telecom",
        "Notes": "Resellers",
        "Units": 4,
        "Name": "Get Solar Inc",
        "Animal": "Vacas",
        "Amount": 7670,
        "Food Quantity": "0.165",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1485,
        "age": 20,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Urinary Problems",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 2,
        "Name": "Discovery Systems",
        "Animal": "Caballos",
        "Amount": 4690,
        "Food Quantity": "0.124",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1486,
        "age": 20,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Manufacturing",
        "Notes": "Direct",
        "Units": 1,
        "Name": "Johnson & Assoc",
        "Animal": "Caballos",
        "Amount": 1930,
        "Food Quantity": "0.228",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1487,
        "age": 8,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Arthritis",
        "Breed": "Health",
        "Notes": "Consultants",
        "Units": 4,
        "Name": "Apollo Inc",
        "Animal": "Caballos",
        "Amount": 9400,
        "Food Quantity": "0.24",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1488,
        "age": 7,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Health",
        "Notes": "Direct",
        "Units": 4,
        "Name": "Get Solar Inc",
        "Animal": "Cabras",
        "Amount": 6450,
        "Food Quantity": "0.3142857142857142857142857143",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1489,
        "age": 0,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Banking",
        "Notes": "Consultants",
        "Units": 2,
        "Name": "Columbia Solar",
        "Animal": "Pavos",
        "Amount": 3910,
        "Food Quantity": "0.2622222222222222222222222222",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1490,
        "age": 18,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Banking",
        "Notes": "Consultants",
        "Units": 3,
        "Name": "Beacon Systems",
        "Animal": "Caballos",
        "Amount": 6890,
        "Food Quantity": "0.244",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1491,
        "age": 0,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Arthritis",
        "Breed": "Banking",
        "Notes": "Resellers",
        "Units": 3,
        "Name": "Beacon Systems",
        "Animal": "Pavos",
        "Amount": 6350,
        "Food Quantity": "0.1777777777777777777777777778",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1492,
        "age": 12,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Urinary Problems",
        "Breed": "Health",
        "Notes": "VARs",
        "Units": 1,
        "Name": "Market Eco",
        "Animal": "Pavos",
        "Amount": 1950,
        "Food Quantity": "0.1333333333333333333333333333",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1493,
        "age": 7,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 3,
        "Name": "Apollo Inc",
        "Animal": "Vacas",
        "Amount": 5640,
        "Food Quantity": "0.18",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1494,
        "age": 8,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Insurance",
        "Notes": "Consultants",
        "Units": 1,
        "Name": "Green Energy Inc",
        "Animal": "Caballos",
        "Amount": 1920,
        "Food Quantity": "0.232",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1495,
        "age": 5,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Health",
        "Notes": "VARs",
        "Units": 1,
        "Name": "Health Plus Inc",
        "Animal": "Caballos",
        "Amount": 1930,
        "Food Quantity": "0.228",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1496,
        "age": 13,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Banking",
        "Notes": "Consultants",
        "Units": 1,
        "Name": "Beacon Systems",
        "Animal": "Pavos",
        "Amount": 1750,
        "Food Quantity": "0.2222222222222222222222222222",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1497,
        "age": 15,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Telecom",
        "Notes": "Resellers",
        "Units": 1,
        "Name": "Arthur & Sons",
        "Animal": "Pavos",
        "Amount": 1820,
        "Food Quantity": "0.1911111111111111111111111111",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1498,
        "age": 10,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Arthritis",
        "Breed": "Health",
        "Notes": "Consultants",
        "Units": 2,
        "Name": "Market Eco",
        "Animal": "Caballos",
        "Amount": 4800,
        "Food Quantity": "0.08",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1499,
        "age": 13,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Insurance",
        "Notes": "Retail",
        "Units": 2,
        "Name": "System Integrators",
        "Animal": "Pavos",
        "Amount": 3940,
        "Food Quantity": "0.2488888888888888888888888889",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1500,
        "age": 9,
        "gender": "Male",
        "type": "Bird"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Telecom",
        "Notes": "VARs",
        "Units": 4,
        "Name": "Beacon Systems",
        "Animal": "Caballos",
        "Amount": 9530,
        "Food Quantity": "0.188",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1501,
        "age": 12,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Health",
        "Notes": "VARs",
        "Units": 4,
        "Name": "Health Plus Inc",
        "Animal": "Vacas",
        "Amount": 7720,
        "Food Quantity": "0.14",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1502,
        "age": 2,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Insurance",
        "Notes": "Direct",
        "Units": 1,
        "Name": "Get Solar Inc",
        "Animal": "Vacas",
        "Amount": 1290,
        "Food Quantity": "0.355",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1503,
        "age": 17,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Urinary Problems",
        "Breed": "Health",
        "Notes": "Direct",
        "Units": 3,
        "Name": "Apollo Inc",
        "Animal": "Gallinas",
        "Amount": 4270,
        "Food Quantity": "0.1533333333333333333333333333",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1504,
        "age": 19,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Insurance",
        "Notes": "Resellers",
        "Units": 1,
        "Name": "System Integrators",
        "Animal": "Caballos",
        "Amount": 1770,
        "Food Quantity": "0.292",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1505,
        "age": 5,
        "gender": "Male",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Health",
        "Notes": "VARs",
        "Units": 1,
        "Name": "System Integrators",
        "Animal": "Caballos",
        "Amount": 2320,
        "Food Quantity": "0.072",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1506,
        "age": 7,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Banking",
        "Notes": "Resellers",
        "Units": 3,
        "Name": "Green Energy Inc",
        "Animal": "Vacas",
        "Amount": 5310,
        "Food Quantity": "0.345",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1507,
        "age": 3,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Health",
        "Notes": "VARs",
        "Units": 2,
        "Name": "Mercury Solar",
        "Animal": "Pavos",
        "Amount": 4140,
        "Food Quantity": "0.16",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1508,
        "age": 6,
        "gender": "Female",
        "type": "Bird"
      },
      {
        "Medical Conditions": "Obesity",
        "Breed": "Telecom",
        "Notes": "Direct",
        "Units": 3,
        "Name": "Energy Systems",
        "Animal": "Caballos",
        "Amount": 7190,
        "Food Quantity": "0.124",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1509,
        "age": 13,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "Diabetes",
        "Breed": "Health",
        "Notes": "Consultants",
        "Units": 3,
        "Name": "Health Plus Inc",
        "Animal": "Vacas",
        "Amount": 5360,
        "Food Quantity": "0.32",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1510,
        "age": 7,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Banking",
        "Notes": "Resellers",
        "Units": 3,
        "Name": "Supply Warehous",
        "Animal": "Caballos",
        "Amount": 7070,
        "Food Quantity": "0.172",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1511,
        "age": 19,
        "gender": "Female",
        "type": "Mammal"
      },
      {
        "Medical Conditions": "None",
        "Breed": "Banking",
        "Notes": "VARs",
        "Units": 1,
        "Name": "Mercury Solar",
        "Animal": "Pavos",
        "Amount": 1590,
        "Food Quantity": "0.2933333333333333333333333333",
        "BirthDate": "2020-05-15T00:00:00",
        "Gender": [],
        "Id": 1512,
        "age": 11,
        "gender": "Female",
        "type": "Bird"
      }
  ]
