// {
//     "name": "Pedigree 100g",
//     "photo": "https://images-na.ssl-images-amazon.com/images/I/812PqI0PadL._AC_UL604_SR604,400_.jpg",
//     "Note": "",
//     "Quantity": 54,
//     "Animal": "food"
// },
export const InventoryData =
[
  {
      "Medical Conditions": "Obesity",
      "Breed": "Manufacturing",
      "Notes": "Resellers",
      "Units": 3,
      "Name": "Adi Devonna",
      "Animal": "Gallinas",
      "Amount": 4670,
      "Food Quantity": "0.3314285714285714285714285714",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1476,
      "age": 11,
      "gender": "Female",
      "type": "Bird",
      "name": "Rey Bobbette"
  },
  {
      "Medical Conditions": "Arthritis",
      "Breed": "Telecom",
      "Notes": "Consultants",
      "Units": 2,
      "Name": "Mala Elbertina",
      "Animal": "Gallinas",
      "Amount": 4440,
      "Food Quantity": "0.224",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1477,
      "age": 16,
      "gender": "Male",
      "type": "Bird",
      "name": "Codie Gusella"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Telecom",
      "Notes": "Direct",
      "Units": 4,
      "Name": "Carroll Tova",
      "Animal": "Gallinas",
      "Amount": 8280,
      "Food Quantity": "0.32",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1478,
      "age": 0,
      "gender": "Female",
      "type": "Bird",
      "name": "Eolande Etheline"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Telecom",
      "Notes": "Retail",
      "Units": 1,
      "Name": "Noelle May",
      "Animal": "Gallinas",
      "Amount": 1590,
      "Food Quantity": "0.205",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1479,
      "age": 9,
      "gender": "Male",
      "type": "Bird",
      "name": "Annette Lane"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 2,
      "Name": "Sallyann Piper",
      "Animal": "Gallinas",
      "Amount": 4390,
      "Food Quantity": "0.244",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1480,
      "age": 9,
      "gender": "Male",
      "type": "Bird",
      "name": "Tandi Edi"
  },
  {
      "Medical Conditions": "Urinary Problems",
      "Breed": "Telecom",
      "Notes": "Direct",
      "Units": 2,
      "Name": "Blinnie Consuela",
      "Animal": "Gallinas",
      "Amount": 3720,
      "Food Quantity": "0.14",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1481,
      "age": 6,
      "gender": "Male",
      "type": "Bird",
      "name": "Ulrica Sonnie"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Health",
      "Notes": "Direct",
      "Units": 3,
      "Name": "Grayce Letisha",
      "Animal": "Gallinas",
      "Amount": 4810,
      "Food Quantity": "0.2514285714285714285714285714",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1482,
      "age": 1,
      "gender": "Female",
      "type": "Bird",
      "name": "Maude Nelia"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 3,
      "Name": "Rochette Tanitansy",
      "Animal": "Gallinas",
      "Amount": 6470,
      "Food Quantity": "0.1244444444444444444444444444",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1483,
      "age": 4,
      "gender": "Male",
      "type": "Bird",
      "name": "Lanette Shantee"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Health",
      "Notes": "VARs",
      "Units": 4,
      "Name": "Feodora Naomi",
      "Animal": "Gallinas",
      "Amount": 6580,
      "Food Quantity": "0.24",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1484,
      "age": 20,
      "gender": "Male",
      "type": "Bird",
      "name": "Tiffy Michaella"
  },
  {
      "Medical Conditions": "Arthritis",
      "Breed": "Telecom",
      "Notes": "Resellers",
      "Units": 4,
      "Name": "Tandy Terese",
      "Animal": "Gallinas",
      "Amount": 7670,
      "Food Quantity": "0.165",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1485,
      "age": 16,
      "gender": "Male",
      "type": "Bird",
      "name": "Eachelle Ailis"
  },
  {
      "Medical Conditions": "Urinary Problems",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 2,
      "Name": "Latisha Ilene",
      "Animal": "Gallinas",
      "Amount": 4690,
      "Food Quantity": "0.124",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1486,
      "age": 16,
      "gender": "Female",
      "type": "Bird",
      "name": "Valeria Veronique"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Manufacturing",
      "Notes": "Direct",
      "Units": 1,
      "Name": "Tandie Kira",
      "Animal": "Gallinas",
      "Amount": 1930,
      "Food Quantity": "0.228",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1487,
      "age": 5,
      "gender": "Female",
      "type": "Bird",
      "name": "Piper Brandice"
  },
  {
      "Medical Conditions": "Arthritis",
      "Breed": "Health",
      "Notes": "Consultants",
      "Units": 4,
      "Name": "Keri Annabel",
      "Animal": "Gallinas",
      "Amount": 9400,
      "Food Quantity": "0.24",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1488,
      "age": 0,
      "gender": "Male",
      "type": "Bird",
      "name": "Kaylyn Sonnie"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Health",
      "Notes": "Direct",
      "Units": 4,
      "Name": "Daffie Corabella",
      "Animal": "Gallinas",
      "Amount": 6450,
      "Food Quantity": "0.3142857142857142857142857143",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1489,
      "age": 10,
      "gender": "Female",
      "type": "Bird",
      "name": "Meggy Lesly"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Banking",
      "Notes": "Consultants",
      "Units": 2,
      "Name": "Salli Kathryne",
      "Animal": "Gallinas",
      "Amount": 3910,
      "Food Quantity": "0.2622222222222222222222222222",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1490,
      "age": 7,
      "gender": "Male",
      "type": "Bird",
      "name": "Emmye Rosalia"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Banking",
      "Notes": "Consultants",
      "Units": 3,
      "Name": "Adora Agnese",
      "Animal": "Gallinas",
      "Amount": 6890,
      "Food Quantity": "0.244",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1491,
      "age": 2,
      "gender": "Male",
      "type": "Bird",
      "name": "Brandie Alison"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Manufacturing",
      "Notes": "Resellers",
      "Units": 3,
      "Name": "Cherri Randa",
      "Animal": "Obejas",
      "Amount": 4670,
      "Food Quantity": "0.3314285714285714285714285714",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1476,
      "age": 8,
      "gender": "Male",
      "type": "Mammal",
      "name": "Michal Melissa"
  },
  {
      "Medical Conditions": "Arthritis",
      "Breed": "Telecom",
      "Notes": "Consultants",
      "Units": 2,
      "Name": "Melissa Melicent",
      "Animal": "Obejas",
      "Amount": 4440,
      "Food Quantity": "0.224",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1477,
      "age": 0,
      "gender": "Male",
      "type": "Mammal",
      "name": "Karrah Cyb"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Telecom",
      "Notes": "Direct",
      "Units": 4,
      "Name": "Cordelia Rhea",
      "Animal": "Obejas",
      "Amount": 8280,
      "Food Quantity": "0.32",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1478,
      "age": 20,
      "gender": "Male",
      "type": "Mammal",
      "name": "Lissy Dena"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Telecom",
      "Notes": "Retail",
      "Units": 1,
      "Name": "Myrna Tonie",
      "Animal": "Obejas",
      "Amount": 1590,
      "Food Quantity": "0.205",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1479,
      "age": 7,
      "gender": "Male",
      "type": "Mammal",
      "name": "Saree Allyce"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 2,
      "Name": "Sheelah Laraine",
      "Animal": "Obejas",
      "Amount": 4390,
      "Food Quantity": "0.244",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1480,
      "age": 20,
      "gender": "Female",
      "type": "Mammal",
      "name": "Drucill Janna"
  },
  {
      "Medical Conditions": "Urinary Problems",
      "Breed": "Telecom",
      "Notes": "Direct",
      "Units": 2,
      "Name": "Gennifer Luci",
      "Animal": "Obejas",
      "Amount": 3720,
      "Food Quantity": "0.14",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1481,
      "age": 19,
      "gender": "Female",
      "type": "Mammal",
      "name": "Ronnica Annalise"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Health",
      "Notes": "Direct",
      "Units": 3,
      "Name": "Ronna Selma",
      "Animal": "Obejas",
      "Amount": 4810,
      "Food Quantity": "0.2514285714285714285714285714",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1482,
      "age": 11,
      "gender": "Male",
      "type": "Mammal",
      "name": "Christabel Blanche"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 3,
      "Name": "Allison Lanni",
      "Animal": "Obejas",
      "Amount": 6470,
      "Food Quantity": "0.1244444444444444444444444444",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1483,
      "age": 5,
      "gender": "Female",
      "type": "Mammal",
      "name": "Dru Mag"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Health",
      "Notes": "VARs",
      "Units": 4,
      "Name": "Paige Cari",
      "Animal": "Obejas",
      "Amount": 6580,
      "Food Quantity": "0.24",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1484,
      "age": 20,
      "gender": "Male",
      "type": "Mammal",
      "name": "Bella Celinda"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Manufacturing",
      "Notes": "Resellers",
      "Units": 3,
      "Name": "Annaliese Trenna",
      "Animal": "Gansos",
      "Amount": 4670,
      "Food Quantity": "0.3314285714285714285714285714",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1476,
      "age": 15,
      "gender": "Female",
      "type": "Bird",
      "name": "Christy Laurice"
  },
  {
      "Medical Conditions": "Arthritis",
      "Breed": "Telecom",
      "Notes": "Consultants",
      "Units": 2,
      "Name": "Leoline Bobbi",
      "Animal": "Gansos",
      "Amount": 4440,
      "Food Quantity": "0.224",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1477,
      "age": 7,
      "gender": "Female",
      "type": "Bird",
      "name": "Prissie Kakalina"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Telecom",
      "Notes": "Direct",
      "Units": 4,
      "Name": "Aurelia Cate",
      "Animal": "Gansos",
      "Amount": 8280,
      "Food Quantity": "0.32",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1478,
      "age": 0,
      "gender": "Male",
      "type": "Bird",
      "name": "Carmina Christyna"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Telecom",
      "Notes": "Retail",
      "Units": 1,
      "Name": "Robena Melisse",
      "Animal": "Gansos",
      "Amount": 1590,
      "Food Quantity": "0.205",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1479,
      "age": 9,
      "gender": "Female",
      "type": "Bird",
      "name": "Marieann Tanya"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 2,
      "Name": "Eda Nariko",
      "Animal": "Gansos",
      "Amount": 4390,
      "Food Quantity": "0.244",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1480,
      "age": 2,
      "gender": "Male",
      "type": "Bird",
      "name": "Malory Jonell"
  },
  {
      "Medical Conditions": "Urinary Problems",
      "Breed": "Telecom",
      "Notes": "Direct",
      "Units": 2,
      "Name": "Adriane Shelli",
      "Animal": "Gansos",
      "Amount": 3720,
      "Food Quantity": "0.14",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1481,
      "age": 2,
      "gender": "Male",
      "type": "Bird",
      "name": "Joyann Judi"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Health",
      "Notes": "Direct",
      "Units": 3,
      "Name": "Petronella Mirabella",
      "Animal": "Gansos",
      "Amount": 4810,
      "Food Quantity": "0.2514285714285714285714285714",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1482,
      "age": 15,
      "gender": "Female",
      "type": "Bird",
      "name": "Evonne Lona"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 3,
      "Name": "Trixy Devinne",
      "Animal": "Gansos",
      "Amount": 6470,
      "Food Quantity": "0.1244444444444444444444444444",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1483,
      "age": 16,
      "gender": "Female",
      "type": "Bird",
      "name": "Karil Maitilde"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Health",
      "Notes": "VARs",
      "Units": 4,
      "Name": "Barb Marcella",
      "Animal": "Gansos",
      "Amount": 6580,
      "Food Quantity": "0.24",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1484,
      "age": 10,
      "gender": "Female",
      "type": "Bird",
      "name": "Coreen Alejandra"
  },
  {
      "Medical Conditions": "Arthritis",
      "Breed": "Telecom",
      "Notes": "Resellers",
      "Units": 4,
      "Name": "Sheelagh Willy",
      "Animal": "Gansos",
      "Amount": 7670,
      "Food Quantity": "0.165",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1485,
      "age": 8,
      "gender": "Female",
      "type": "Bird",
      "name": "Kacy Shanon"
  },
  {
      "Medical Conditions": "Urinary Problems",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 2,
      "Name": "Anya Saidee",
      "Animal": "Gansos",
      "Amount": 4690,
      "Food Quantity": "0.124",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1486,
      "age": 17,
      "gender": "Male",
      "type": "Bird",
      "name": "Ciel Wini"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Manufacturing",
      "Notes": "Direct",
      "Units": 1,
      "Name": "Lynnelle Vanna",
      "Animal": "Gansos",
      "Amount": 1930,
      "Food Quantity": "0.228",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1487,
      "age": 0,
      "gender": "Male",
      "type": "Bird",
      "name": "Sioux Shawna"
  },
  {
      "Medical Conditions": "Arthritis",
      "Breed": "Health",
      "Notes": "Consultants",
      "Units": 4,
      "Name": "Issy Clarice",
      "Animal": "Gansos",
      "Amount": 9400,
      "Food Quantity": "0.24",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1488,
      "age": 13,
      "gender": "Female",
      "type": "Bird",
      "name": "Brittany Carlita"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Health",
      "Notes": "Direct",
      "Units": 4,
      "Name": "Ermengarde Donnie",
      "Animal": "Gansos",
      "Amount": 6450,
      "Food Quantity": "0.3142857142857142857142857143",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1489,
      "age": 4,
      "gender": "Female",
      "type": "Bird",
      "name": "Mahala Liuka"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Banking",
      "Notes": "Consultants",
      "Units": 2,
      "Name": "Toma Wynnie",
      "Animal": "Gansos",
      "Amount": 3910,
      "Food Quantity": "0.2622222222222222222222222222",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1490,
      "age": 18,
      "gender": "Male",
      "type": "Bird",
      "name": "Gayla Charissa"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Banking",
      "Notes": "Consultants",
      "Units": 3,
      "Name": "Ivonne Nicky",
      "Animal": "Gansos",
      "Amount": 6890,
      "Food Quantity": "0.244",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1491,
      "age": 3,
      "gender": "Female",
      "type": "Bird",
      "name": "Keelia Perl"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Manufacturing",
      "Notes": "Resellers",
      "Units": 3,
      "Name": "Cybill Maritsa",
      "Animal": "Cabras",
      "Amount": 4670,
      "Food Quantity": "0.3314285714285714285714285714",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1476,
      "age": 2,
      "gender": "Male",
      "type": "Mammal",
      "name": "Blanca Eimile"
  },
  {
      "Medical Conditions": "Arthritis",
      "Breed": "Telecom",
      "Notes": "Consultants",
      "Units": 2,
      "Name": "Madelaine Dawna",
      "Animal": "Caballos",
      "Amount": 4440,
      "Food Quantity": "0.224",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1477,
      "age": 4,
      "gender": "Female",
      "type": "Mammal",
      "name": "Giralda Jenilee"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Telecom",
      "Notes": "Direct",
      "Units": 4,
      "Name": "Viviene Valentina",
      "Animal": "Pavos",
      "Amount": 8280,
      "Food Quantity": "0.32",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1478,
      "age": 6,
      "gender": "Female",
      "type": "Bird",
      "name": "Joleen Diane-Marie"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Telecom",
      "Notes": "Retail",
      "Units": 1,
      "Name": "Min Florie",
      "Animal": "Vacas",
      "Amount": 1590,
      "Food Quantity": "0.205",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1479,
      "age": 20,
      "gender": "Male",
      "type": "Mammal",
      "name": "Bunnie Perri"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 2,
      "Name": "Eleni Kippie",
      "Animal": "Caballos",
      "Amount": 4390,
      "Food Quantity": "0.244",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1480,
      "age": 11,
      "gender": "Female",
      "type": "Mammal",
      "name": "Fara Valaree"
  },
  {
      "Medical Conditions": "Urinary Problems",
      "Breed": "Telecom",
      "Notes": "Direct",
      "Units": 2,
      "Name": "Julienne Tamma",
      "Animal": "Vacas",
      "Amount": 3720,
      "Food Quantity": "0.14",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1481,
      "age": 3,
      "gender": "Male",
      "type": "Mammal",
      "name": "Vivyan Dorris"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Health",
      "Notes": "Direct",
      "Units": 3,
      "Name": "Shoshana Kathie",
      "Animal": "Cabras",
      "Amount": 4810,
      "Food Quantity": "0.2514285714285714285714285714",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1482,
      "age": 17,
      "gender": "Male",
      "type": "Mammal",
      "name": "Adelice Minda"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 3,
      "Name": "Hildy Trisha",
      "Animal": "Pavos",
      "Amount": 6470,
      "Food Quantity": "0.1244444444444444444444444444",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1483,
      "age": 13,
      "gender": "Female",
      "type": "Bird",
      "name": "Alverta Maryanne"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Health",
      "Notes": "VARs",
      "Units": 4,
      "Name": "Annette Gretal",
      "Animal": "Cabras",
      "Amount": 6580,
      "Food Quantity": "0.24",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1484,
      "age": 14,
      "gender": "Female",
      "type": "Mammal",
      "name": "Sukey Noreen"
  },
  {
      "Medical Conditions": "Arthritis",
      "Breed": "Telecom",
      "Notes": "Resellers",
      "Units": 4,
      "Name": "Dorisa Deeyn",
      "Animal": "Vacas",
      "Amount": 7670,
      "Food Quantity": "0.165",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1485,
      "age": 20,
      "gender": "Female",
      "type": "Mammal",
      "name": "Latisha Mollie"
  },
  {
      "Medical Conditions": "Urinary Problems",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 2,
      "Name": "Dierdre Rivi",
      "Animal": "Caballos",
      "Amount": 4690,
      "Food Quantity": "0.124",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1486,
      "age": 20,
      "gender": "Male",
      "type": "Mammal",
      "name": "Margette Dionis"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Manufacturing",
      "Notes": "Direct",
      "Units": 1,
      "Name": "Moira Barbaraanne",
      "Animal": "Caballos",
      "Amount": 1930,
      "Food Quantity": "0.228",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1487,
      "age": 8,
      "gender": "Male",
      "type": "Mammal",
      "name": "Iolanthe Miran"
  },
  {
      "Medical Conditions": "Arthritis",
      "Breed": "Health",
      "Notes": "Consultants",
      "Units": 4,
      "Name": "Cissiee Oralia",
      "Animal": "Caballos",
      "Amount": 9400,
      "Food Quantity": "0.24",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1488,
      "age": 7,
      "gender": "Male",
      "type": "Mammal",
      "name": "Atlanta Pearline"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Health",
      "Notes": "Direct",
      "Units": 4,
      "Name": "Wren Cammi",
      "Animal": "Cabras",
      "Amount": 6450,
      "Food Quantity": "0.3142857142857142857142857143",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1489,
      "age": 0,
      "gender": "Female",
      "type": "Mammal",
      "name": "Rheta Tamiko"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Banking",
      "Notes": "Consultants",
      "Units": 2,
      "Name": "Pia Felecia",
      "Animal": "Pavos",
      "Amount": 3910,
      "Food Quantity": "0.2622222222222222222222222222",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1490,
      "age": 18,
      "gender": "Male",
      "type": "Bird",
      "name": "Elmira Evangelia"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Banking",
      "Notes": "Consultants",
      "Units": 3,
      "Name": "Demetris Loralee",
      "Animal": "Caballos",
      "Amount": 6890,
      "Food Quantity": "0.244",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1491,
      "age": 0,
      "gender": "Male",
      "type": "Mammal",
      "name": "Esta Aila"
  },
  {
      "Medical Conditions": "Arthritis",
      "Breed": "Banking",
      "Notes": "Resellers",
      "Units": 3,
      "Name": "Zarah Tomi",
      "Animal": "Pavos",
      "Amount": 6350,
      "Food Quantity": "0.1777777777777777777777777778",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1492,
      "age": 12,
      "gender": "Female",
      "type": "Bird",
      "name": "Consolata Helge"
  },
  {
      "Medical Conditions": "Urinary Problems",
      "Breed": "Health",
      "Notes": "VARs",
      "Units": 1,
      "Name": "Lani Rozella",
      "Animal": "Pavos",
      "Amount": 1950,
      "Food Quantity": "0.1333333333333333333333333333",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1493,
      "age": 7,
      "gender": "Male",
      "type": "Bird",
      "name": "Brietta Dulcine"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 3,
      "Name": "Loise Carol-Jean",
      "Animal": "Vacas",
      "Amount": 5640,
      "Food Quantity": "0.18",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1494,
      "age": 8,
      "gender": "Female",
      "type": "Mammal",
      "name": "Indira Sile"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Insurance",
      "Notes": "Consultants",
      "Units": 1,
      "Name": "Tuesday Deane",
      "Animal": "Caballos",
      "Amount": 1920,
      "Food Quantity": "0.232",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1495,
      "age": 5,
      "gender": "Male",
      "type": "Mammal",
      "name": "Shannon Benedicta"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Health",
      "Notes": "VARs",
      "Units": 1,
      "Name": "Erda Minetta",
      "Animal": "Caballos",
      "Amount": 1930,
      "Food Quantity": "0.228",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1496,
      "age": 13,
      "gender": "Female",
      "type": "Mammal",
      "name": "Annadiane Jeane"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Banking",
      "Notes": "Consultants",
      "Units": 1,
      "Name": "Anne-Corinne Rubia",
      "Animal": "Pavos",
      "Amount": 1750,
      "Food Quantity": "0.2222222222222222222222222222",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1497,
      "age": 15,
      "gender": "Male",
      "type": "Bird",
      "name": "Ninetta Adriena"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Telecom",
      "Notes": "Resellers",
      "Units": 1,
      "Name": "Genny Gussy",
      "Animal": "Pavos",
      "Amount": 1820,
      "Food Quantity": "0.1911111111111111111111111111",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1498,
      "age": 10,
      "gender": "Male",
      "type": "Bird",
      "name": "Farand Celeste"
  },
  {
      "Medical Conditions": "Arthritis",
      "Breed": "Health",
      "Notes": "Consultants",
      "Units": 2,
      "Name": "Leland Brande",
      "Animal": "Caballos",
      "Amount": 4800,
      "Food Quantity": "0.08",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1499,
      "age": 13,
      "gender": "Female",
      "type": "Mammal",
      "name": "Alex Mickie"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Insurance",
      "Notes": "Retail",
      "Units": 2,
      "Name": "Rhianna Crista",
      "Animal": "Pavos",
      "Amount": 3940,
      "Food Quantity": "0.2488888888888888888888888889",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1500,
      "age": 9,
      "gender": "Male",
      "type": "Bird",
      "name": "Zarla Jessamine"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Telecom",
      "Notes": "VARs",
      "Units": 4,
      "Name": "Deloris Gay",
      "Animal": "Caballos",
      "Amount": 9530,
      "Food Quantity": "0.188",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1501,
      "age": 12,
      "gender": "Female",
      "type": "Mammal",
      "name": "Consuelo Edie"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Health",
      "Notes": "VARs",
      "Units": 4,
      "Name": "Perri Kim",
      "Animal": "Vacas",
      "Amount": 7720,
      "Food Quantity": "0.14",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1502,
      "age": 2,
      "gender": "Male",
      "type": "Mammal",
      "name": "Marielle Eachelle"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Insurance",
      "Notes": "Direct",
      "Units": 1,
      "Name": "Cammi Roseanne",
      "Animal": "Vacas",
      "Amount": 1290,
      "Food Quantity": "0.355",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1503,
      "age": 17,
      "gender": "Male",
      "type": "Mammal",
      "name": "Florance Mignonne"
  },
  {
      "Medical Conditions": "Urinary Problems",
      "Breed": "Health",
      "Notes": "Direct",
      "Units": 3,
      "Name": "Charmane Maybelle",
      "Animal": "Gallinas",
      "Amount": 4270,
      "Food Quantity": "0.1533333333333333333333333333",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1504,
      "age": 19,
      "gender": "Female",
      "type": "Bird",
      "name": "Katerina Maurene"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Insurance",
      "Notes": "Resellers",
      "Units": 1,
      "Name": "Drusy Larine",
      "Animal": "Caballos",
      "Amount": 1770,
      "Food Quantity": "0.292",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1505,
      "age": 5,
      "gender": "Male",
      "type": "Mammal",
      "name": "Mara Larina"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Health",
      "Notes": "VARs",
      "Units": 1,
      "Name": "Nonah Modesta",
      "Animal": "Caballos",
      "Amount": 2320,
      "Food Quantity": "0.072",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1506,
      "age": 7,
      "gender": "Female",
      "type": "Mammal",
      "name": "Starla Dotti"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Banking",
      "Notes": "Resellers",
      "Units": 3,
      "Name": "Reba Aryn",
      "Animal": "Vacas",
      "Amount": 5310,
      "Food Quantity": "0.345",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1507,
      "age": 3,
      "gender": "Female",
      "type": "Mammal",
      "name": "Nell Shayna"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Health",
      "Notes": "VARs",
      "Units": 2,
      "Name": "Abbie Valerye",
      "Animal": "Pavos",
      "Amount": 4140,
      "Food Quantity": "0.16",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1508,
      "age": 6,
      "gender": "Female",
      "type": "Bird",
      "name": "Verena Almeta"
  },
  {
      "Medical Conditions": "Obesity",
      "Breed": "Telecom",
      "Notes": "Direct",
      "Units": 3,
      "Name": "Cris Zorina",
      "Animal": "Caballos",
      "Amount": 7190,
      "Food Quantity": "0.124",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1509,
      "age": 13,
      "gender": "Female",
      "type": "Mammal",
      "name": "Marrilee Collie"
  },
  {
      "Medical Conditions": "Diabetes",
      "Breed": "Health",
      "Notes": "Consultants",
      "Units": 3,
      "Name": "Else Sybilla",
      "Animal": "Vacas",
      "Amount": 5360,
      "Food Quantity": "0.32",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1510,
      "age": 7,
      "gender": "Female",
      "type": "Mammal",
      "name": "Ricky Joby"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Banking",
      "Notes": "Resellers",
      "Units": 3,
      "Name": "Ofilia Astrix",
      "Animal": "Caballos",
      "Amount": 7070,
      "Food Quantity": "0.172",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1511,
      "age": 19,
      "gender": "Female",
      "type": "Mammal",
      "name": "Olympe Neda"
  },
  {
      "Medical Conditions": "None",
      "Breed": "Banking",
      "Notes": "VARs",
      "Units": 1,
      "Name": "Mireille Alida",
      "Animal": "Pavos",
      "Amount": 1590,
      "Food Quantity": "0.2933333333333333333333333333",
      "BirthDate": "2020-05-15T00:00:00",
      "Gender": [],
      "Id": 1512,
      "age": 11,
      "gender": "Female",
      "type": "Bird",
      "name": "Eustacia Martguerita"
  }
]
