export const TasksData = [
    {
       "Task_ID":1,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":1,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Prepare 2022 Financial",
       "Task_Description":"<div>IMPORTANT: The document must be fully formatted in Excel.</div>",
       "Task_Start_Date":"2022-01-15T00:00:00",
       "Task_Due_Date":"2022-01-31T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2014-01-20T00:00:00",
       "Task_Reminder_Time":"1899-12-30T08:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG1k="
    },
    {
       "Task_ID":2,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":1,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Prepare 3013 Marketing Plan",
       "Task_Description":"<div>We need to double revenues in 2022 and our marketing strategy is going to be key here. R&amp;D is improving existing products and creating new products so we can deliver great AV equipment to our customers.</div>\r\n\r\n<div>Robert, please make certain to create a PowerPoint presentation for the members of the executive team.</div>",
       "Task_Start_Date":"2022-01-01T00:00:00",
       "Task_Due_Date":"2022-01-31T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG1o="
    },
    {
       "Task_ID":3,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":1,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Update Personnel Files",
       "Task_Description":"<div>In an audit I conducted of personnel files this, I found documentation to be lacking. Samantha, you need to review my report and get this fixed.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Samantha Bright: John, I've completed this review and sent my report to you.</div>",
       "Task_Start_Date":"2022-02-03T00:00:00",
       "Task_Due_Date":"2022-02-28T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-02-27T00:00:00",
       "Task_Reminder_Time":"1899-12-30T09:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG1s="
    },
    {
       "Task_ID":4,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":1,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Review Health Insurance Options Under the Affordable Care Act",
       "Task_Description":"<div>The changes in health insurance laws require that we review our existing coverage and update it to meet regulations. &nbsp;Samantha Bright will be point on this.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Samantha Bright: Update - still working with the insurance company to update our coverages.</div>",
       "Task_Start_Date":"2022-02-12T00:00:00",
       "Task_Due_Date":"2022-04-25T00:00:00",
       "Task_Status":"In Progress",
       "Task_Priority":4,
       "Task_Completion":50,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2014-04-23T00:00:00",
       "Task_Reminder_Time":"1899-12-30T09:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG1w="
    },
    {
       "Task_ID":5,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":2,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Choose between PPO and HMO Health Plan",
       "Task_Description":"<div>We need a final decision on whether we are planning on staying with a PPO Health Plan or we plan on switching to an HMO. We cannot proceed with compliance with the Affordable Health Act until we make this decision.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>John Heart: Samantha, I'm still reviewing costs. I am not in a position to make a final decision at this point.</div>",
       "Task_Start_Date":"2022-02-15T00:00:00",
       "Task_Due_Date":"2022-04-15T00:00:00",
       "Task_Status":"In Progress",
       "Task_Priority":4,
       "Task_Completion":75,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG10="
    },
    {
       "Task_ID":6,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":4,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Google AdWords Strategy",
       "Task_Description":"<div>Make final decision on whether we are going to increase our Google AdWord spend based on our 2022 marketing plan. </div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>We must seriously consider a higher spend if we are going to double revenues this year.</div>",
       "Task_Start_Date":"2022-02-16T00:00:00",
       "Task_Due_Date":"2022-02-28T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG14="
    },
    {
       "Task_ID":7,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":4,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"New Brochures",
       "Task_Description":"<div>Review and the new brochure designs and give final approval. &nbsp;</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>John Heart: I've reviewed them all and forwarded an email with all changes we need to make to the brochures to comply with local regulations.</div>",
       "Task_Start_Date":"2022-02-17T00:00:00",
       "Task_Due_Date":"2022-02-24T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-02-24T00:00:00",
       "Task_Reminder_Time":"1899-12-30T10:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG5I="
    },
    {
       "Task_ID":8,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":1,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"2022 Brochure Designs",
       "Task_Description":"<div>The changes we need to make to our 2022 brochures have been forwarded via Email please review and send updated versions to Robert Reagan.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Morgan Kennedy: This task has been completed. New designs are published on our server.</div>",
       "Task_Start_Date":"2022-02-19T00:00:00",
       "Task_Due_Date":"2022-02-24T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":3,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAGA8="
    },
    {
       "Task_ID":9,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":28,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Brochure Design Review",
       "Task_Description":"<div>We have been instructed by management to modify brochure designs for 2022. All specifications and change requests are on the server.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Violet Bailey: What did you want me to do besides create the icons we'll be using in the brochure?</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Morgan Kennedy: That's it. Thanks</div>",
       "Task_Start_Date":"2022-02-19T00:00:00",
       "Task_Due_Date":"2022-02-22T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG5M="
    },
    {
       "Task_ID":10,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":28,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Website Re-Design Plan",
       "Task_Description":"<div>The changes in our brochure designs for 2022 require us to update key areas of our website. </div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Violet Bailey: I've completed the plan and have submitted it to Robert for his approval.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>&nbsp;</div>",
       "Task_Start_Date":"2022-02-19T00:00:00",
       "Task_Due_Date":"2022-02-24T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-02-24T00:00:00",
       "Task_Reminder_Time":"1899-12-30T11:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG18="
    },
    {
       "Task_ID":11,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":1,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Rollout of New Website and Marketing Brochures",
       "Task_Description":"<div>The designs for new brochures and website have been approved. Launch date is set for Feb 28.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Robert Reagan: Designers and IT departments have implemented all requirements. The rollout is complete.</div>",
       "Task_Start_Date":"2022-02-20T00:00:00",
       "Task_Due_Date":"2022-02-28T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG2A="
    },
    {
       "Task_ID":12,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":4,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Update Sales Strategy Documents",
       "Task_Description":"<div>Changes in marketing strategy require an update to our direct sales strategy. The report has to be completed by month's end to submission to the CEO.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Ed Holmes: As you will see in my report, I do not recommend any major changes. </div>",
       "Task_Start_Date":"2022-02-20T00:00:00",
       "Task_Due_Date":"2022-02-22T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-02-20T00:00:00",
       "Task_Reminder_Time":"1899-12-30T10:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG5Q="
    },
    {
       "Task_ID":13,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":8,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Create 2012 Sales Report",
       "Task_Description":"<div>2012 Sales Report has to be completed so we can determine if major changes are required to sales strategy. </div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Jim Packard: I've forwarded everything I have via Email. If you need anything else, please let em know.</div>",
       "Task_Start_Date":"2022-02-20T00:00:00",
       "Task_Due_Date":"2022-02-21T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-02-21T00:00:00",
       "Task_Reminder_Time":"1899-12-30T15:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG5U="
    },
    {
       "Task_ID":14,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":41,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Direct vs Online Sales Comparison Report",
       "Task_Description":"<div>To better understand 2022 sales strategy, we need to report 2012 direct vs online sales information to management.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Hannah Brookly: Jim, I created this a long time ago and I've forwarded it to you again. Let me know if it's sufficient.</div>",
       "Task_Start_Date":"2022-02-20T00:00:00",
       "Task_Due_Date":"2022-02-22T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG2E="
    },
    {
       "Task_ID":15,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":41,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Review 2012 Sales Report and Approve 2022 Plans",
       "Task_Description":"<div>2012 Sales Reports along with detailed market comparisons are complete. Management needs to review and provide additional guidance.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Robert Reagan: We are in agreement with the recommendations in the report. You are go to execute plans.</div>",
       "Task_Start_Date":"2022-02-23T00:00:00",
       "Task_Due_Date":"2022-02-28T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-02-27T00:00:00",
       "Task_Reminder_Time":"1899-12-30T09:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG5Y="
    },
    {
       "Task_ID":16,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":1,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Deliver R&D Plans for 2022",
       "Task_Description":"<div>Marketing strategy is set. R&amp;D needs to deliver a detailed report on product development plans along with final decisions as to which product lines will be terminated.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Arther Miller: I've submitted your reports. Need final approval.</div>",
       "Task_Start_Date":"2022-03-01T00:00:00",
       "Task_Due_Date":"2022-03-10T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG2I="
    },
    {
       "Task_ID":17,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":3,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Create 2022 R&D Plans",
       "Task_Description":"<div>Create 2022 R&amp;D Plan Report for CEO and include information on products under consideration and final decisions as to which products will be depracated.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Bart Arnaz: Done. You should review this Arthur as there are issues we need to consider.</div>",
       "Task_Start_Date":"2022-03-01T00:00:00",
       "Task_Due_Date":"2022-03-07T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-03-06T00:00:00",
       "Task_Reminder_Time":"1899-12-30T12:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG5c="
    },
    {
       "Task_ID":18,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":32,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"2022 QA Strategy Report",
       "Task_Description":"<div>In final stages of the 2022 R&amp;D Report to Management. Need QA strategy report asap. Remember, 2012 was a difficult year product quality-wise and we must step it up in 2022.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Leah Simpson: Bart, my apologies about 2012. My report includes remedies to issues we encountered.</div>",
       "Task_Start_Date":"2022-03-02T00:00:00",
       "Task_Due_Date":"2022-03-05T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-03-05T00:00:00",
       "Task_Reminder_Time":"1899-12-30T14:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG5g="
    },
    {
       "Task_ID":19,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":33,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"2022 Training Events",
       "Task_Description":"<div>Need to finalize 2022 Training Events. QA is under pressure to step it up in 2022 and without an effective training strategy for the field, QA problems will persist.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Nat Maguiree: Leah, we've forwarded our 2022 training schedule. We'll do our best to minimize issues in 2022.</div>",
       "Task_Start_Date":"2022-03-02T00:00:00",
       "Task_Due_Date":"2022-03-04T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG2M="
    },
    {
       "Task_ID":20,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":31,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Approve Hiring of John Jeffers",
       "Task_Description":"<div>Review resume and non-compete with previous employer and give final approval to hire John Jeffers.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Greta Sims: We are unable to hire John. His non-compete is rock solid and he will not be able to perform his role as a product trainer for our company.</div>",
       "Task_Start_Date":"2022-03-02T00:00:00",
       "Task_Due_Date":"2022-03-12T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-03-12T00:00:00",
       "Task_Reminder_Time":"1899-12-30T16:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG5k="
    },
    {
       "Task_ID":21,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":5,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Non-Compete Agreements",
       "Task_Description":"<div>Make final decision on whether our employees should sign non-compete agreements. </div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Samantha Bright: Greta, we discussed this and we feel it is unnecessary to require non-compete agreements for employees.</div>",
       "Task_Start_Date":"2022-03-12T00:00:00",
       "Task_Due_Date":"2022-03-14T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":1,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG/Y="
    },
    {
       "Task_ID":22,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":2,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Update NDA Agreement",
       "Task_Description":"<div>Need sign-off on the new NDA agreement. It's important that this is done quickly to prevent any unauthorized leaks.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>John Heart: Done. Please have Greta update employee files.</div>",
       "Task_Start_Date":"2022-03-14T00:00:00",
       "Task_Due_Date":"2022-03-16T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-03-15T00:00:00",
       "Task_Reminder_Time":"1899-12-30T09:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG2Q="
    },
    {
       "Task_ID":23,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":2,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Update Employee Files with New NDA",
       "Task_Description":"<div>Management has approved new NDA. All employees must sign the new NDA and their employee files must be updated.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Greta Sims: Having difficulty with a few employees. Will follow up by Email.</div>",
       "Task_Start_Date":"2022-03-16T00:00:00",
       "Task_Due_Date":"2022-03-26T00:00:00",
       "Task_Status":"Need Assistance",
       "Task_Priority":2,
       "Task_Completion":90,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG5o="
    },
    {
       "Task_ID":24,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":5,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Sign Updated NDA",
       "Task_Description":"<div>You must sign updated NDA. Documents have been emailed to you. Once documents have been signed, please retain one copy for your records and return one to HR for filing.</div>",
       "Task_Start_Date":"2022-03-20T00:00:00",
       "Task_Due_Date":"2022-03-25T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":3,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAGBA="
    },
    {
       "Task_ID":25,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":5,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Sign Updated NDA",
       "Task_Description":"<div><font color=black>You must sign updated NDA. Documents have been emailed to you. Once documents have been signed, please retain one copy for your records and return one to HR for filing.</font></div>",
       "Task_Start_Date":"2022-03-20T00:00:00",
       "Task_Due_Date":"2022-03-25T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":3,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-03-25T00:00:00",
       "Task_Reminder_Time":"1899-12-30T11:00:00",
       "SSMA_TimeStamp":"AAAAAAAAGBE="
    },
    {
       "Task_ID":26,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":5,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Sign Updated NDA",
       "Task_Description":"<div><font color=black>You must sign updated NDA. Documents have been emailed to you. Once documents have been signed, please retain one copy for your records and return one to HR for filing.</font></div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div><font color=black>Ed Holmes: As discussed, I don't believe the new NDA is helpful for our sales strategy.</font></div>",
       "Task_Start_Date":"2022-03-20T00:00:00",
       "Task_Due_Date":"2022-03-25T00:00:00",
       "Task_Status":"Need Assistance",
       "Task_Priority":3,
       "Task_Completion":25,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAGBI="
    },
    {
       "Task_ID":27,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":5,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Sign Updated NDA",
       "Task_Description":"<div><font color=black>You must sign updated NDA. Documents have been emailed to you. Once documents have been signed, please retain one copy for your records and return one to HR for filing.</font></div>",
       "Task_Start_Date":"2022-03-20T00:00:00",
       "Task_Due_Date":"2022-03-25T00:00:00",
       "Task_Status":"In Progress",
       "Task_Priority":3,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-03-25T00:00:00",
       "Task_Reminder_Time":"1899-12-30T08:00:00",
       "SSMA_TimeStamp":"AAAAAAAAGBM="
    },
    {
       "Task_ID":28,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":9,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Submit Questions Regarding New NDA",
       "Task_Description":"<div>The new NDA is now required for employment. I need a list of questions or issues so we can submit all paperwork to HR.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Kelly Rodriguez: I don’t have any questions. Thank you.</div>",
       "Task_Start_Date":"2022-03-21T00:00:00",
       "Task_Due_Date":"2022-03-24T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG2U="
    },
    {
       "Task_ID":29,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":9,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Submit Questions Regarding New NDA",
       "Task_Description":"<div><font color=black>The new NDA is now required for employment. I need a list of questions or issues so we can submit all paperwork to HR.</font></div>",
       "Task_Start_Date":"2022-03-21T00:00:00",
       "Task_Due_Date":"2022-03-24T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-03-24T00:00:00",
       "Task_Reminder_Time":"1899-12-30T17:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG2Y="
    },
    {
       "Task_ID":30,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":9,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Submit Questions Regarding New NDA",
       "Task_Description":"<div><font color=black>The new NDA is now required for employment. I need a list of questions or issues so we can submit all paperwork to HR.</font></div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div><font color=black>Anthony Remmen: My attorney suggests that I not sign this. </font></div>",
       "Task_Start_Date":"2022-03-21T00:00:00",
       "Task_Due_Date":"2022-03-24T00:00:00",
       "Task_Status":"Need Assistance",
       "Task_Priority":4,
       "Task_Completion":25,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG2c="
    },
    {
       "Task_ID":31,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":10,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Submit Signed NDA",
       "Task_Description":"<div>The new NDA must be signed for continued employment at DevAV. Do not ignore this task as you will be terminated if not signed. </div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>The sensitive nature of our job responsibilities demands that we hold ourselves to the highest standards.</div>",
       "Task_Start_Date":"2022-03-22T00:00:00",
       "Task_Due_Date":"2022-03-24T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":3,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-03-23T00:00:00",
       "Task_Reminder_Time":"1899-12-30T11:00:00",
       "SSMA_TimeStamp":"AAAAAAAAGBQ="
    },
    {
       "Task_ID":32,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":10,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Submit Signed NDA",
       "Task_Description":"<div><font color=black>The new NDA must be signed for continued employment at DevAV. Do not ignore this task as you will be terminated if not signed. </font></div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div><font color=black>The sensitive nature of our job responsibilities demands that we hold ourselves to the highest standards.</font></div>",
       "Task_Start_Date":"2022-03-22T00:00:00",
       "Task_Due_Date":"2022-03-24T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":3,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAGBU="
    },
    {
       "Task_ID":33,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":10,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Submit Signed NDA",
       "Task_Description":"<div><font color=black>The new NDA must be signed for continued employment at DevAV. Do not ignore this task as you will be terminated if not signed. </font></div>\r\n\r\n<div><font color=black>&nbsp;</font></div>\r\n\r\n<div><font color=black>The sensitive nature of our job responsibilities demands that we hold ourselves to the highest standards.</font></div>",
       "Task_Start_Date":"2022-03-22T00:00:00",
       "Task_Due_Date":"2022-03-24T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":3,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-03-23T00:00:00",
       "Task_Reminder_Time":"1899-12-30T13:00:00",
       "SSMA_TimeStamp":"AAAAAAAAGBY="
    },
    {
       "Task_ID":34,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":10,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Submit Signed NDA",
       "Task_Description":"<div><font color=black>The new NDA must be signed for continued employment at DevAV. Do not ignore this task as you will be terminated if not signed. </font></div>\r\n\r\n<div><font color=black>&nbsp;</font></div>\r\n\r\n<div><font color=black>The sensitive nature of our job responsibilities demands that we hold ourselves to the highest standards.</font></div>",
       "Task_Start_Date":"2022-03-22T00:00:00",
       "Task_Due_Date":"2022-03-24T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":3,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAGBc="
    },
    {
       "Task_ID":35,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":1,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Update Revenue Projections",
       "Task_Description":"<div>Meeting with Board has been scheduled. Need final sales projections for 2022.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Sandra Johnson: Report has been emailed to all stakeholders.</div>",
       "Task_Start_Date":"2022-03-24T00:00:00",
       "Task_Due_Date":"2022-04-07T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG5s="
    },
    {
       "Task_ID":36,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":7,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Review Revenue Projections",
       "Task_Description":"<div>Board requires 2022 Revenue Projection Report. Review sales reports and my projections and give final approval before I proceed.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Ed Holmes: Done. You are 100% on target with the data.</div>",
       "Task_Start_Date":"2022-03-25T00:00:00",
       "Task_Due_Date":"2022-04-06T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-04-06T00:00:00",
       "Task_Reminder_Time":"1899-12-30T08:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG2g="
    },
    {
       "Task_ID":37,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":7,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Comment on Revenue Projections",
       "Task_Description":"<div><font color=black>Board requires 2022 Revenue Projection Report. Comment on sales reports and my projections and provide any additional information that might be relevant to management.</font></div>",
       "Task_Start_Date":"2022-03-25T00:00:00",
       "Task_Due_Date":"2022-04-03T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":3,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAGBg="
    },
    {
       "Task_ID":38,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":7,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Comment on Revenue Projections",
       "Task_Description":"<div><font color=black>Board requires 2022 Revenue Projection Report. Comment on sales reports and my projections and provide any additional information that might be relevant to management.</font></div>",
       "Task_Start_Date":"2022-03-25T00:00:00",
       "Task_Due_Date":"2022-04-03T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":3,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-04-03T00:00:00",
       "Task_Reminder_Time":"1899-12-30T13:30:00",
       "SSMA_TimeStamp":"AAAAAAAAGBk="
    },
    {
       "Task_ID":39,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":7,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Comment on Revenue Projections",
       "Task_Description":"<div><font color=black>Board requires 2022 Revenue Projection Report. Comment on sales reports and my projections and provide any additional information that might be relevant to management.</font></div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div><font color=black>Sandra Johnson: Todd, I need this information from you. You are holding up my report. I will have to go without your input if I do not receive it.</font></div>",
       "Task_Start_Date":"2022-03-25T00:00:00",
       "Task_Due_Date":"2022-04-03T00:00:00",
       "Task_Status":"Deferred",
       "Task_Priority":3,
       "Task_Completion":25,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAGBo="
    },
    {
       "Task_ID":40,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":11,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Provide New Health Insurance Docs",
       "Task_Description":"<div>Need to get employees to sign new health insurance documents. Need final paperwork from agents.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Greta Sims: Cindy, this information was already sent to you. Do not create unnecessary tasks for me.</div>",
       "Task_Start_Date":"2022-03-28T00:00:00",
       "Task_Due_Date":"2022-04-07T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG5w="
    },
    {
       "Task_ID":41,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":11,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Review Changes to Health Insurance Coverage",
       "Task_Description":"<div>Shipping department must review new health insurance policy and submit paperwork by the end of the month. If not submitted, coverage will terminate.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Kevin Carter: All employees have submitted paperwork.</div>",
       "Task_Start_Date":"2022-04-07T00:00:00",
       "Task_Due_Date":"2022-04-30T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-04-15T00:00:00",
       "Task_Reminder_Time":"1899-12-30T15:30:00",
       "SSMA_TimeStamp":"AAAAAAAAG50="
    },
    {
       "Task_ID":42,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":10,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Scan Health Insurance Forms",
       "Task_Description":"<div>HR needs scanned copies of all signed documents for personnel files. Victor, you have to scan them for me as I'm just too busy.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Victor Norris: Done and forwarded by Email.</div>",
       "Task_Start_Date":"2022-04-15T00:00:00",
       "Task_Due_Date":"2022-04-20T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-04-15T00:00:00",
       "Task_Reminder_Time":"1899-12-30T16:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG54="
    },
    {
       "Task_ID":43,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":14,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Sign Health Insurance Forms",
       "Task_Description":"<div>Kevin asked me to collect all signed health insurance forms for him - he is too busy. Please get this done asap so I can get back to my regular job.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Mary Stern: Done and Email sent.</div>",
       "Task_Start_Date":"2022-04-16T00:00:00",
       "Task_Due_Date":"2022-04-19T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG2k="
    },
    {
       "Task_ID":44,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":14,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Sign Health Insurance Forms",
       "Task_Description":"<div><font color=black>Kevin asked me to collect all signed health insurance forms for him - he is too busy. Please get this done asap so I can get back to my regular job.</font></div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div><font color=black>Davey Jones: Done and Email sent.</font></div>",
       "Task_Start_Date":"2022-04-16T00:00:00",
       "Task_Due_Date":"2022-04-19T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG2o="
    },
    {
       "Task_ID":45,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":14,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Sign Health Insurance Forms",
       "Task_Description":"<div><font color=black>Kevin asked me to collect all signed health insurance forms for him - he is too busy. Please get this done asap so I can get back to my regular job.</font></div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div><font color=black>Robin Cosworth: I'm going with my husband's plan. This new plan is terrible and I don’t want it.</font></div>",
       "Task_Start_Date":"2022-04-16T00:00:00",
       "Task_Due_Date":"2022-04-19T00:00:00",
       "Task_Status":"Deferred",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG2s="
    },
    {
       "Task_ID":46,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":9,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Follow up with West Coast Stores",
       "Task_Description":"<div>The problem with the TVs has been confirmed with R&amp;D. We need to immediately follow up with West Coast Retailers and let them know so we do not get any returns.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>James Anderson: This is going to take me a long time to finish.</div>",
       "Task_Start_Date":"2022-04-18T00:00:00",
       "Task_Due_Date":"2014-02-04T00:00:00",
       "Task_Status":"In Progress",
       "Task_Priority":3,
       "Task_Completion":95,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAGBs="
    },
    {
       "Task_ID":47,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":9,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Follow up with East Coast Stores",
       "Task_Description":"<div><font color=black>The problem with the TVs has been confirmed with R&amp;D. We need to immediately follow up with West Coast Retailers and let them know so we do not get any returns.</font></div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div><font color=black>Kelly Rodriguez: Still working on this. Taking so much time. </font></div>",
       "Task_Start_Date":"2022-04-18T00:00:00",
       "Task_Due_Date":"2014-01-04T00:00:00",
       "Task_Status":"In Progress",
       "Task_Priority":3,
       "Task_Completion":85,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAGBw="
    },
    {
       "Task_ID":48,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":9,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Send Email to Customers about Recall",
       "Task_Description":"<div><font color=black>The problem with the TVs has been confirmed with R&amp;D. We need to send an email to all customers who purchased the TV in the last 30 days.</font></div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div><font color=black>Anthony Remmen: Done. Over 100 emails have been sent.</font></div>",
       "Task_Start_Date":"2022-04-18T00:00:00",
       "Task_Due_Date":"2022-04-30T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG2w="
    },
    {
       "Task_ID":49,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":7,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Submit Refund Report for 2022 Recall",
       "Task_Description":"<div>Need a report on all customers who've been promised a refund as a result of the 2022 TV recall.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Barb Banks: Sent by Email. I know, this is going to hurt our bottom-line.</div>",
       "Task_Start_Date":"2022-04-25T00:00:00",
       "Task_Due_Date":"2022-05-05T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":3,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-05-05T00:00:00",
       "Task_Reminder_Time":"1899-12-30T11:30:00",
       "SSMA_TimeStamp":"AAAAAAAAGB0="
    },
    {
       "Task_ID":50,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":7,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Give Final Approval for Refunds",
       "Task_Description":"<div>Refunds as a result of our 2022 TV recalls have been submitted. Need final approval to cut checks to customers.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Samantha Bright: You can send the checks out mid-May.</div>",
       "Task_Start_Date":"2022-05-05T00:00:00",
       "Task_Due_Date":"2022-05-15T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-05-15T00:00:00",
       "Task_Reminder_Time":"1899-12-30T12:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG58="
    },
    {
       "Task_ID":51,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":3,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Prepare Product Recall Report",
       "Task_Description":"<div>Bart, this recall was an absolute disaster. Your report better be on my desk tomorrow. This is killing our bottom-line.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Bart Arnaz: Yes, it's unacceptable.</div>",
       "Task_Start_Date":"2022-05-10T00:00:00",
       "Task_Due_Date":"2022-05-16T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-05-16T00:00:00",
       "Task_Reminder_Time":"1899-12-30T16:30:00",
       "SSMA_TimeStamp":"AAAAAAAAG6A="
    },
    {
       "Task_ID":52,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":3,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Review Product Recall Report by Engineering Team",
       "Task_Description":"<div>John, everyone in Engineering is working hard to avoid any future recalls. Can you please review this report and send me your thoughts.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>John Heart: Very difficult situation. It should never have happened.</div>",
       "Task_Start_Date":"2022-05-17T00:00:00",
       "Task_Due_Date":"2022-05-20T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG20="
    },
    {
       "Task_ID":53,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":32,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Create Training Course for New TVs",
       "Task_Description":"<div>After the recall, customers have option to purchase new version of TV. You need to prepare training course for our retail partners so they can better understand the design changes.</div>",
       "Task_Start_Date":"2022-05-29T00:00:00",
       "Task_Due_Date":"2022-06-29T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG6E="
    },
    {
       "Task_ID":54,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":31,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Review Training Course for any Ommissions",
       "Task_Description":"<div>Leah, consider this most important item on your agenda. I need this new training material reviewed so it can be submitted to management.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Leah Simpson: I only found a few spelling mistakes.</div>",
       "Task_Start_Date":"2022-06-01T00:00:00",
       "Task_Due_Date":"2022-06-15T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":3,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAGB4="
    },
    {
       "Task_ID":55,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":5,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Review Overtime Report",
       "Task_Description":"<div>Brett, way too much overtime being submitted by the IT department please review numbers and get with management and tell me long term decision on this matter.</div>",
       "Task_Start_Date":"2022-06-10T00:00:00",
       "Task_Due_Date":"2022-06-14T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-06-14T00:00:00",
       "Task_Reminder_Time":"1899-12-30T17:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG6I="
    },
    {
       "Task_ID":56,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":6,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Submit Overtime Request Forms",
       "Task_Description":"<div>Taylor, you are working too many hours and management wants to stop it. You cannot work this much overtime. Send me the report so I can kick it up to HR.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>They need you to justify your hours.</div>",
       "Task_Start_Date":"2022-06-11T00:00:00",
       "Task_Due_Date":"2022-06-12T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-06-12T00:00:00",
       "Task_Reminder_Time":"1899-12-30T14:30:00",
       "SSMA_TimeStamp":"AAAAAAAAG6M="
    },
    {
       "Task_ID":57,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":6,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Submit Overtime Request Forms",
       "Task_Description":"<div><font color=black>Amelia, you are working too many hours and management wants to stop it. You cannot work this much overtime. Send me the report so I can kick it up to HR.</font></div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div><font color=black>They need you to justify your hours.</font></div>",
       "Task_Start_Date":"2022-06-11T00:00:00",
       "Task_Due_Date":"2022-06-12T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-06-12T00:00:00",
       "Task_Reminder_Time":"1899-12-30T15:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG6Q="
    },
    {
       "Task_ID":58,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":6,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Submit Overtime Request Forms",
       "Task_Description":"<div><font color=black>Wally, you are working too many hours and management wants to stop it. You cannot work this much overtime. Send me the report so I can kick it up to HR.</font></div>\r\n\r\n<div><font color=black>&nbsp;</font></div>\r\n\r\n<div><font color=black>They need you to justify your hours.</font></div>",
       "Task_Start_Date":"2022-06-11T00:00:00",
       "Task_Due_Date":"2022-06-12T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG6U="
    },
    {
       "Task_ID":59,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":6,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Overtime Approval Guidelines",
       "Task_Description":"<div>Samantha, we cannot keep going like this. Everytime my people send overtime request, we get hassled. Can you please send me the definitive guide as to when people can submit overtime?</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Samantha Bright: Done. Check Email.</div>",
       "Task_Start_Date":"2022-06-15T00:00:00",
       "Task_Due_Date":"2022-06-20T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG6Y="
    },
    {
       "Task_ID":60,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":12,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Refund Request Template",
       "Task_Description":"<div>We need to update the refund request template as I keep getting asked questions from confused customers. Is this something we can do this week?</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Ed Holmes: I've asked for input from legal. For now it's status quo.</div>",
       "Task_Start_Date":"2022-06-17T00:00:00",
       "Task_Due_Date":"2014-04-01T00:00:00",
       "Task_Status":"Deferred",
       "Task_Priority":2,
       "Task_Completion":0,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2014-04-01T00:00:00",
       "Task_Reminder_Time":"1899-12-30T09:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG6c="
    },
    {
       "Task_ID":61,
       "Task_Assigned_Employee":"Marcos",
       "Task_Owner_ID":12,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Recall Rebate Form",
       "Task_Description":"<div>I don’t think we can keep sending our existing rebate forms. Like the refund request forms, customers are confused by all the legal language and they refuse to sign it.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Ed Holmes: We have nothing from legal on this and so we have to keep doing what we've been doing.</div>",
       "Task_Start_Date":"2022-06-17T00:00:00",
       "Task_Due_Date":"2014-04-01T00:00:00",
       "Task_Status":"Deferred",
       "Task_Priority":2,
       "Task_Completion":0,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2014-04-01T00:00:00",
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG6g="
    },
    {
       "Task_ID":62,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":30,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Create Report on Customer Feedback",
       "Task_Description":"<div>Ed asked me to get with you and prepare a full report of all questions being asked by customers about the recall and refund request forms. Legal does not want to take any action until we submit this.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Sammy Hill: This is crazy. I don’t understand why legal does not change the language.</div>",
       "Task_Start_Date":"2022-06-20T00:00:00",
       "Task_Due_Date":"2022-06-30T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":4,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG24="
    },
    {
       "Task_ID":63,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":30,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Review Customer Feedback Report",
       "Task_Description":"<div>The problems with our recall and refund request forms are real. Sale staff are overwhelmed and are answering the same questions over and over again. Need a solution from legal.</div>",
       "Task_Start_Date":"2022-06-30T00:00:00",
       "Task_Due_Date":"2022-07-03T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-07-03T00:00:00",
       "Task_Reminder_Time":"1899-12-30T10:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG6k="
    },
    {
       "Task_ID":64,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":8,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Customer Feedback Report Analysis",
       "Task_Description":"<div>We've analyzed all complaints submitted to sales staff. The problems are real and a solution is needed. Kicking this up to you John as legal simply will not budge.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>John Heart: Ed, I'm with legal on this. Tell the sales staff to keep doing what they are doing.</div>",
       "Task_Start_Date":"2022-07-05T00:00:00",
       "Task_Due_Date":"2014-04-09T00:00:00",
       "Task_Status":"Deferred",
       "Task_Priority":2,
       "Task_Completion":0,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG6o="
    },
    {
       "Task_ID":65,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":8,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Prepare Shipping Cost Analysis Report",
       "Task_Description":"<div>Management needs to see which shipping company is giving us the best bang for our buck. Need the report asap as we have to commit to one shipper soon.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Kevin Carter: They are all the same, but the report has been prepared nonetheless.</div>",
       "Task_Start_Date":"2022-07-10T00:00:00",
       "Task_Due_Date":"2022-07-15T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-07-15T00:00:00",
       "Task_Reminder_Time":"1899-12-30T11:30:00",
       "SSMA_TimeStamp":"AAAAAAAAG6s="
    },
    {
       "Task_ID":66,
       "Task_Assigned_Employee":"Diego",
       "Task_Owner_ID":10,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Provide Feedback on Shippers",
       "Task_Description":"<div>Need to know which shipping companies you prefer to work. Looks like costs are all coming in the same so I think we just need to pick the one that offers the best services.</div>",
       "Task_Start_Date":"2022-07-11T00:00:00",
       "Task_Due_Date":"2022-07-14T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG6w="
    },
    {
       "Task_ID":67,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":10,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Provide Feedback on Shippers",
       "Task_Description":"<div><font color=black>Need to know which shipping companies you prefer to work. Looks like costs are all coming in the same so I think we just need to pick the one that offers the best services.</font></div>",
       "Task_Start_Date":"2022-07-11T00:00:00",
       "Task_Due_Date":"2022-07-14T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":false,
       "Task_Reminder_Date":null,
       "Task_Reminder_Time":null,
       "SSMA_TimeStamp":"AAAAAAAAG60="
    },
    {
       "Task_ID":68,
       "Task_Assigned_Employee":"Fremiud",
       "Task_Owner_ID":10,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Provide Feedback on Shippers",
       "Task_Description":"<div><font color=black>Need to know which shipping companies you prefer to work. Looks like costs are all coming in the same so I think we just need to pick the one that offers the best services.</font></div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div><font color=black>Robin Cosworth: You already know my opinion Kevin. Why keep asking me about this?</font></div>",
       "Task_Start_Date":"2022-07-11T00:00:00",
       "Task_Due_Date":"2022-07-14T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-07-14T00:00:00",
       "Task_Reminder_Time":"1899-12-30T10:30:00",
       "SSMA_TimeStamp":"AAAAAAAAG64="
    },
    {
       "Task_ID":69,
       "Task_Assigned_Employee":"Pedro",
       "Task_Owner_ID":10,
       "Task_Customer_Employee_ID":null,
       "Task_Subject":"Select Preferred Shipper",
       "Task_Description":"<div>All cost analysis reports have been prepared. I've also submitted personal opinions on all the shippers we've dealt with. We need a final decision so I can negotiate final contract.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Samantha Bright: This is not just up to me. Will take it CEO.</div>",
       "Task_Start_Date":"2022-07-16T00:00:00",
       "Task_Due_Date":"2022-07-20T00:00:00",
       "Task_Status":"Completed",
       "Task_Priority":2,
       "Task_Completion":100,
       "Task_Reminder":true,
       "Task_Reminder_Date":"2022-07-20T00:00:00",
       "Task_Reminder_Time":"1899-12-30T08:00:00",
       "SSMA_TimeStamp":"AAAAAAAAG68="
    }
 ]